In [1]:
import pandas as pd 
import numpy as np
import math
import cmath
import scipy.io as sio
import random
from multiprocessing import Pool

In [2]:
## Loading of ideal: Ideal of algebraic cycles, Ideal of the sum of coefficients for the monomial a_i
### This is part is without the correction

#ruta=open("/home/daniel/Desktop/Sextic_quarfold_Computation/Computation_of_determinant/Ideal_sum_of_coeff_of_alg_cycles_matrix_without_the_correction.txt","r")
#Idictm0=ruta.read()
#Idictm0=Idictm0.split(",")
#Idictm0=np.array(Idictm0)
#Idictm0=np.reshape(Idictm0, (1751, 1751))

#x=2**(1/3)
#y=cmath.exp(2j*math.pi/12)
#z=x+y

## Evaluation of Idictm in z
#IdictEv0=np.zeros((1751,1751), dtype=complex)
#for i in range(0,1751):
 #   for k in range(0,1751):
  #      IdictEv0[i,k]=eval(Idictm0[i,k].replace("^", "**"))
#np.savetxt('Ideal_sum_of_coeff_of_alg_cycles_matrix_evaluated_in_z_without_the_correction.txt', IdictEv0)

In [3]:
## Loading of ideal: Ideal of algebraic cycles, Ideal of the sum of coefficients for the monomial a_i
### This is part is with the correction

#ruta=open("/home/daniel/Desktop/Sextic_quarfold_Computation/Computation_of_determinant/Ideal_sum_of_coeff_of_alg_cycles_matrix_with_the_correction.txt","r")
#Idictm1=ruta.read()
#Idictm1=Idictm1.split(",")
#Idictm1=np.array(Idictm1)
#Idictm1=np.reshape(Idictm1, (1751, 1751))

#x=2**(1/3)
#y=cmath.exp(2j*math.pi/12)
#z=x+y

## Evaluation of Idictm in z
#IdictEv1=np.zeros((1751,1751), dtype=complex)
#for i in range(0,1751):
 #   for k in range(0,1751):
  #      IdictEv1[i,k]=eval(Idictm1[i,k].replace("^", "**"))
#np.savetxt('Ideal_sum_of_coeff_of_alg_cycles_matrix_evaluated_in_z_with_the_correction.txt', IdictEv1)

In [4]:
##Loading the Ideal dictionary evaluated in z=x+y, where x=2**(1/3) y=cmath.exp(2j*math.pi/12)

### Warning: Modify this rute:
ruta='Ideal_sum_of_coeff_of_alg_cycles_matrix_evaluated_in_z_without_the_correction.txt'
IdictEv0=np.loadtxt(ruta,dtype=complex) ## without the correction

ruta='Ideal_sum_of_coeff_of_alg_cycles_matrix_evaluated_in_z_with_the_correction.txt'
IdictEv1=np.loadtxt(ruta,dtype=complex) ## with the correction


In [5]:
## Loading the matrix associated with the monomials a_i

### Warning: Modify this rute:
ruta="matrix_monomial_degree_12_in_numbers.txt"
###

Rr=open(ruta,"r")
Mmon=Rr.read()
Mmon=Mmon.replace('0\n','0');
Mmon=Mmon.split(",")
Mmon=np.array(Mmon)
Mmon=np.reshape(Mmon, (426, 426))
#print(Mmon[0:15,0:15])

In [6]:
## Loading  matriz A associated to xtAx<=216

### Warning: Modify this rute:
#ruta="/home/daniel/QuarticSixtic/Determinante_de_matrix_de_monomios/IntAlgMatrix.mat"
ruta='/home/daniel/Desktop/Sextic_quarfold_Computation/Intersection_matrices/Intersection_matrix.mat'
###

##La matriz A, con la correccion del ciclo lineal
mat = sio.loadmat(ruta)
#I0=mat['IMalg']
I0=mat['IM']
A1 = np.asmatrix(I0)       ## with the correction



##La matriz A, sin la correccion del ciclo lineal
ruta='/home/daniel/Desktop/Sextic_quarfold_Computation/Intersection_matrices/Intersection_matrix_without_the_translation.mat';
mat = sio.loadmat(ruta)
#I0=mat['IMalg']
I1=mat['IM1']
A0 = np.asmatrix(I1)      ## without the correction



In [7]:
## Function which computes the matrix of monomial evaluated in the point [c(1)...c(1751)]
def computation_monomial_matriz(IalgEv,Mmon,IdictEv):
    ## Evaluation of Ideal of the sum of coefficients for the monomial a_i
    v=np.transpose(np.asmatrix(IalgEv));
    Evaluation=IdictEv*v;
    
    ## Construction of matrix of monomials
    Meval=np.zeros((426,426), dtype=complex)
    for k in range(426):
        for l in range(426):
            Mkl=int(Mmon[k,l])
            if Mkl>0:
                Meval[k,l]=Evaluation[Mkl-1]
    return Meval


In [8]:

##### INPUTS########



IalgEv=np.zeros((1751,), dtype=int)



#N=6

#(1,0,2)
LL=[231, 674, 1724, 1741, 1739, 1722]

#(1,0,2)
#LL= [993, 281, 1721, 1738, 1743, 1725] ### Shift: L1= [230, 561, 281] Norm (G+G0): 293.5 Norm G: 316.0



#(2,0,2)
N=8
LL= [840, 922, 659, 761, 1744, 1748, 1728, 1723]#Shift:L1= [168, 594, 922] Norm (G+G0): 293.5 Norm G: 312.0



#N=10
#LL=[189, 307, 68, 173, 219, 244, 1146, 1625, 1732, 1737] # 348.0 ### Shift: j= 244 Norma: 252.0
#LL=[189, 307, 68, 173, 128, 244, 1146, 1625, 1732, 1737] # 350.0 ### Shift: j= 244 Norma: 260.0
#LL=[189, 307, 68, 173, 200, 203, 1146, 1625, 1732, 1737] # 354.0 ### Shift: j= 203 Norma: 258.0
#LL=[189, 307, 68, 173, 9, 161, 1146, 1625, 1732, 1737] # 358.0 ### Shift: j= 161,307 Norma: 262.0
#LL=[189, 307, 68, 173, 686, 592, 1146, 1625, 1732, 1737] # 366.0 ### Shift: j= 592 Norma: 240.0
#LL=[189, 307, 135, 173, 686, 592, 1146, 1625, 1732, 1737] # 366.0 ### Shift: j= 592 Norma: 246.0
#LL=[135, 146, 584, 515, 686, 592, 1146, 1625, 1732, 1737] # 368.0 ### Shift: j= 146 Norma: 260.0



IalgEv=np.zeros((1751,), dtype=int)
for k in range(N):
    IalgEv[LL[k]]=(-1)**k;

##### Computing the determinant and the norm
M0=computation_monomial_matriz(IalgEv,Mmon,IdictEv0) ## without the correction
M1=computation_monomial_matriz(IalgEv,Mmon,IdictEv1) ## with the correction


R0= np.linalg.matrix_rank(M0)
R1= np.linalg.matrix_rank(M1)


print("The rank are:")
print(R0, R1)


vt=np.asmatrix(IalgEv)
v=np.transpose(vt)
Norma0=vt*A0*v
Norma1=vt*A1*v

print("The Norm are:")
print(float(Norma0), float(Norma1))

B=np.zeros((N,N), dtype=float)
for i in range(N):
    for j in range(N):
        B[i,j]=A0[LL[i],LL[j]]
v0=np.zeros((N,), dtype=int); 
for k in range(N):
    v0[k]=(-1)**k;
v0=np.asmatrix(v0);
v0t=np.transpose(v0)
print(B*v0t)

The rank are:
426 426
The Norm are:
312.0 312.0
[[ 18.]
 [-26.]
 [ 21.]
 [-18.]
 [ 55.]
 [-70.]
 [ 75.]
 [-29.]]


In [10]:

B=np.zeros((N,N), dtype=float)
for i in range(N):
    for j in range(N):
        B[i,j]=A0[LL[i],LL[j]]
print(B)

v0=np.zeros((N,), dtype=int); 
for k in range(N):
    v0[k]=(-1)**k;
v0=np.asmatrix(v0);
v0t=np.transpose(v0)
print(v0*B*v0t)

[[ 20.83333333  -0.16666667  -0.16666667  -0.16666667  -1.
    0.          -1.           1.        ]
 [ -0.16666667  20.83333333  -4.16666667   0.83333333   0.
    0.          -2.          -2.        ]
 [ -0.16666667  -4.16666667  20.83333333  -0.16666667   0.
    2.           2.           4.        ]
 [ -0.16666667   0.83333333  -0.16666667  20.83333333   4.
    0.           0.           0.        ]
 [ -1.           0.           0.           4.          96.
   12.           0.          24.        ]
 [  0.           0.           2.           0.          12.
   96.           0.         -12.        ]
 [ -1.          -2.           2.           0.           0.
    0.          96.          24.        ]
 [  1.          -2.           4.           0.          24.
  -12.          24.          96.        ]]
[[312.]]


In [12]:
B=np.zeros((N,N), dtype=float)
for i in range(N):
    for j in range(N):
        B[i,j]=A1[LL[i],LL[j]]
print(B)

v0=np.zeros((N,), dtype=int); 
for k in range(N):
    v0[k]=(-1)**k;
v0=np.asmatrix(v0);
v0t=np.transpose(v0)
print(v0*B*v0t)

[[  42.   21.   21.   21.  251.  252.  251.  253.]
 [  21.   42.   17.   22.  252.  252.  250.  250.]
 [  21.   17.   42.   21.  252.  254.  254.  256.]
 [  21.   22.   21.   42.  256.  252.  252.  252.]
 [ 251.  252.  252.  256. 3096. 3012. 3000. 3024.]
 [ 252.  252.  254.  252. 3012. 3096. 3000. 2988.]
 [ 251.  250.  254.  252. 3000. 3000. 3096. 3024.]
 [ 253.  250.  256.  252. 3024. 2988. 3024. 3096.]]
[[312.]]


In [9]:
#### Generating random vectors linear cycles
N=4 # Number of linear cycles
Mexp=10000000 # Numero de experimetos

def Random_Vectors(i):
    IalgEv=np.zeros((1751,), dtype=int) # Entrada de valores de los ciclos algebraicos
    
    ######### More explicit 
    L=list(range(1001))
    L=random.sample(L, N); 
    IalgEv=np.zeros((1751,), dtype=int)

    IalgEv[L[0]]=1;
    IalgEv[L[1]]=-1;

    IalgEv[L[2]]=1;
    IalgEv[L[3]]=-1;

    IalgEv[1723]=1;
    IalgEv[1728]=-1;

    IalgEv[1731]=1;
    IalgEv[1736]=-1;

    #L=[i,j,rowt3_84[l],colt3_84[l],rowt3_84[m],colt3_84[m]];
    L0=L+[1723,1728,1731,1736];

    vt=np.asmatrix(IalgEv)
    v=np.transpose(vt)
    Norma0=vt*A1*v

    if Norma0<=312:
        M1=computation_monomial_matriz(IalgEv,Mmon,IdictEv0)
        R1= np.linalg.matrix_rank(M1)

        if R1==426:
            print(L0)
            print(Norma0)
            print(R1)

            
with Pool() as pool:
    pool.map(Random_Vectors, range(Mexp))
print('Terminé')


[934, 704, 72, 218, 1723, 1728, 1731, 1736]
[[312.]]
426
Terminé


In [ ]:
##### Computing the varitations of linear cycles
def Variation_of_linear_cycles(i):
    print(i)
    for j in range(i+1,1001):
        for k in range(j+1,1001): ###### CHANGE IT if work with (1,0,2)
            for l in range(k+1,1001):  ###### CHANGE IT if work with (1,0,2)    
                IalgEv=np.zeros((1751,), dtype=int)

                
                ######### For (1,0,2) ########
                #IalgEv[i]=1;
                #IalgEv[j]=-1;
                
                #IalgEv[1729]=1;
                #IalgEv[1748]=-1
                
                #IalgEv[1737]=1;
                #IalgEv[1750]=-1
                
                #L=[i,j,1729,1748,1737,1750]
                ##############################
                

                ########## For (2,0,2) #######
                
                IalgEv[i]=1;
                IalgEv[j]=-1;

                IalgEv[k]=1;
                IalgEv[l]=-1;
                
                IalgEv[1723]=1;
                IalgEv[1728]=-1;

                IalgEv[1731]=1;
                IalgEv[1736]=-1;
                L=[i,j,k,l,1723,1728,1731,1736];
                #########################
             

                vt=np.asmatrix(IalgEv)
                v=np.transpose(vt)
                Norma0=vt*A1*v
                
                if Norma0<=312:
                    M1=computation_monomial_matriz(IalgEv,Mmon,IdictEv0)
                    R1= np.linalg.matrix_rank(M1)

                    if R1==426:
                        print(L)
                        print(Norma0)
                        #print(R1)


with Pool() as pool:
    pool.map(Variation_of_linear_cycles, range(10))  
print('TERMINÉ')


0
2
3
1


In [ ]:
##### Computing the varitations of linear cycles for the new approach
N=6

LL= [1671, 1505, 1747, 1723, 1725, 1727] ### Shift: L1= [900, 913, 870] Norm (G+G0): 353.5 Norm G: 336.0


IalgEv=np.zeros((1751,), dtype=int)
for k in range(N):
    IalgEv[LL[k]]=(-1)**k;

Mexp=1000000
def random_variation_new_approach(i):
    ######### More explicit 
    L1=list(range(1001)); 
    L1=random.sample(L1, 3);      
    ##############################
    
    CycleL0=np.zeros((1751,), dtype=int); 
    CycleL0[L1[0]]= CycleL0[L1[0]]+1; CycleL0[L1[1]]=CycleL0[L1[1]]+1; CycleL0[L1[2]]=CycleL0[L1[2]]+1;
    Cycleshift=np.zeros((1751,), dtype=int);
    Cycleshift=IalgEv+CycleL0;


    ##### Computing the determinant and the norm
    vt=np.asmatrix(Cycleshift); v=np.transpose(vt);
    Norma=vt*A0*v;

    vt0=np.asmatrix(IalgEv); v0=np.transpose(vt0);
    Norma0=vt0*A0*v0;

    if Norma<353.5:
        M0=computation_monomial_matriz(Cycleshift,Mmon,IdictEv0) ## without the correction
        R0= np.linalg.matrix_rank(M0)
        if R0==426:
            print("#LL=",LL, "### Shift:", "L1=",L1, "Norm (G+G0):", Norma[0,0], "Norm G:", Norma0[0,0] )


with Pool() as pool:
    pool.map(random_variation_new_approach, range(Mexp))  
print('TERMINÉ')

In [38]:
#### Computing the second new approach 
#(1,0,2)
#N=6
#LL= [231, 674, 1724, 1741, 1739, 1722] ### Shift: L1= [11, 13, 674] Norm (G+G0): 299.5 Norm G: 312.0
#LL= [993, 281, 1721, 1738, 1743, 1725] ### Shift: L1= [230, 561, 281] Norm (G+G0): 293.5 Norm G: 316.0
#LL=[231, 674, 1724, 1741, 1739, 1722] #LL= [231, 674, 1724, 1741, 1739, 1722] ### Shift: L1= [11, 13, 674] Norm (G+G0): 299.5 Norm G: 312.0




#(2,0,2)
#N=8
#LL= [840, 922, 659, 761, 1744, 1748, 1728, 1723]#Shift:L1= [168, 594, 922] Norm (G+G0): 293.5 Norm G: 312.0
#LL= [840, 922, 659, 761, 1744, 1748, 1728, 1723]#Shift:L1= [168, 658, 922] Norm (G+G0): 293.5 Norm G: 312.0
#LL= [840, 922, 659, 761, 1744, 1748, 1728, 1723]#Shift:L1= [623, 658, 922] Norm (G+G0): 293.5 Norm G: 312.0

#LL= [306, 613, 279, 420, 1723, 1728, 1731, 1736] ### Shift: L1= [54, 100, 613] Norm (G+G0): 315.5 Norm G: 312.0
#LL= [306, 613, 279, 420, 1723, 1728, 1731, 1736] ### Shift: L1= [54, 315, 420] Norm (G+G0): 315.5 Norm G: 312.0


IalgEv=np.zeros((1751,), dtype=int)
for k in range(N):
    IalgEv[LL[k]]=(-1)**k;

def random_variation_second_new_approach(i):
    for j in range(i,1001):
        L1=[i,j,LL[1]];
        CycleL0=np.zeros((1751,), dtype=int); 
        CycleL0[L1[0]]= CycleL0[L1[0]]+1; CycleL0[L1[1]]=CycleL0[L1[1]]+1; CycleL0[L1[2]]=CycleL0[L1[2]]+1;
        Cycleshift=np.zeros((1751,), dtype=int);
        Cycleshift=IalgEv+CycleL0;

        ##### Computing the determinant and the norm
        vt=np.asmatrix(Cycleshift); v=np.transpose(vt);
        Norma=vt*A0*v;
        
        vt0=np.asmatrix(IalgEv); v0=np.transpose(vt0);
        Norma0=vt0*A0*v0;

        if Norma<=315.5:
            M0=computation_monomial_matriz(Cycleshift,Mmon,IdictEv0) ## without the correction
            R0= np.linalg.matrix_rank(M0)
            if R0==426:
                print("#LL=",LL, "### Shift:", "L1=",L1, "Norm (G+G0):", Norma[0,0], "Norm G:", Norma0[0,0] )

with Pool() as pool:
    pool.map(random_variation_second_new_approach, range(1001))  
print('TERMINÉ')

KeyboardInterrupt: 

In [48]:

## Para probar especificamente:
LL= [1671, 1505, 1747, 1723, 1725, 1727] ### Shift: L1= [900, 913, 870] Norm (G+G0): 353.5 Norm G: 336.0


IalgEv=np.zeros((1751,), dtype=int)
for k in range(N):
    IalgEv[LL[k]]=(-1)**k;
    
L1= [900, 913, 870] 
CycleL0=np.zeros((1751,), dtype=int); 
CycleL0[L1[0]]= CycleL0[L1[0]]+1; CycleL0[L1[1]]=CycleL0[L1[1]]+1; CycleL0[L1[2]]=CycleL0[L1[2]]+1;
Cycleshift=np.zeros((1751,), dtype=int);
Cycleshift=IalgEv+CycleL0;

##### Computing the determinant and the norm
vt=np.asmatrix(Cycleshift); v=np.transpose(vt);
Norma=vt*A0*v;
print("Norma=",Norma)


M0=computation_monomial_matriz(Cycleshift,Mmon,IdictEv0) ## without the correction
R0= np.linalg.matrix_rank(M0)
print("Rank=",R0)

Norma= [[353.5]]
Rank= 426
